name: Continuous Integration

on:
  push:
    branches:
    - main
      
jobs:
  pipeline-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Grant executable permissions to tests.sh
      run: chmod +x ./main/project/tests.sh
  
    - name: Run tests
      run: |
        ./main/project/tests.sh
